### ISSUE TITLE
format dans la partie texte des recettes

### ISSUE THREAD

**Issue by ReneePaugam** [brignogan/brignogan.github.io#10]
exemple sur les pages civet et sanglier
insérer mieux les lignes qui ne sont pas dans les listes
et mieux gérer les liste pour le vin

**Comment by pogam** [comment]
pour les espaces dans les recettes entre les listes
voir comment c est fait dans 2019-04-16-sangliersauceveneur.md
il faut ajouter #### devant les sous sections
